In [ ]:
#assignment 1

In [3]:
import numpy as np

In [8]:
def function1():
    arr = np.array([1,7,13,105])
    print(arr)
    print(f"Size = {arr.size}")

In [9]:
function1()

[  1   7  13 105]
Size = 4


In [10]:
#2 Write a NumPy program to create an element-wise comparison (greater,greater_equal, less and less_equal) of two given arrays.


In [11]:
def function2():
    n1 = ([10,20,30,90])
    n2 = ([50,20,60,80])
    print(np.greater(n1,n2))
    print(np.greater_equal(n1,n2))
    print(np.less(n1,n2))
    print(np.less_equal(n1,n2))

In [12]:
function2()

[False False False  True]
[False  True False  True]
[ True False  True False]
[ True  True  True False]


In [13]:
#3 Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives, 10 tens, 10 twentys and 10 fiftys.


In [16]:
def function3():
    arr1 = np.zeros(10)
    arr2 = np.ones(10)
    arr3 = (arr2*5)
    arr4 = (arr2*10)
    arr5 = (arr2*20)
    arr6 = (arr2*50)
    print(arr1)
    print(arr2)
    print(arr3)
    print(arr4)
    print(arr5)
    print(arr6)

In [17]:
function3()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [18]:
#4 Write a NumPy program to create an array of integers from 30 to 70.


In [21]:
def function4():
    arr7 = np.arange(30,70)
    print(arr7)

In [22]:
function4()

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [23]:
#5 Write a NumPy program to create an array of integers from 50 to 95.


In [26]:
def function5():
    arr8 = np.arange(50,95)
    print(arr8)

function5()

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [27]:
#6 Write a NumPy program to create an array of all even integers from 20 to 80.


In [28]:
def function6():
    arr9 = np.arange(20,88)
    print(arr9)

function6()

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87]


In [29]:
#7  Write a NumPy program to create an array of all odd integers from 20 to 80.


In [30]:
def function7():
    arr10 = np.arange(21,81,2)
    print(arr10)

function7()

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [31]:
#8. Write a NumPy program to generate an array of 15 random numbers from 10 to 40.


In [34]:
def function8():
    arr11 = np.random.randint(10,40,15)
    print(arr11)

function8()

[26 22 23 24 22 25 26 39 33 34 31 19 13 15 11]


In [35]:
#9. Write a NumPy program to generate an array of 10 random numbers from 30 to 50.


In [38]:
def function9():
    arr12 = np.random.randint(30,56,10)
    print(arr12)

function9()

[31 35 51 36 46 34 33 32 33 53]


In [39]:
#10. Write a NumPy program to generate an array of 20 random numbers from 50 to 90.


In [41]:
def function10():
    arr13 = np.random.randint(50,90,20)
    print(arr13)

function10()

[74 75 81 70 52 74 64 88 73 63 65 60 62 55 50 78 57 77 63 82]


In [42]:
#11. Create any two arrays & perform various mathematical operations.i.e. Addition, Substraction, Multiplication, Divide.


In [43]:
def function11():
    n1 = np.array([10,20,30,40,50])
    n2 = np.array([2,4,6,8,10])
    print(f"N1 = {n1}")
    print(f"N2 = {n2}")
    print(n1+n2)
    print(n1-n2)
    print(n1*n2)
    print(n1/n2)

function11()

N1 = [10 20 30 40 50]
N2 = [ 2  4  6  8 10]
[12 24 36 48 60]
[ 8 16 24 32 40]
[ 20  80 180 320 500]
[5. 5. 5. 5. 5.]


In [44]:
#12. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.


In [45]:
def function12():
    n1 = np.arange(10,22).reshape(3,4)
    print(n1)

function12()

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [46]:
#13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.


In [51]:
def function13():
     n2 = np.eye(3)
     print(n2)

function13()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
#14. Write a NumPy program to find the number of rows and columns in a given matrix. 


In [54]:
def function14():
    matrix = np.matrix([[10,20,30],[11,22,33]])
    X = matrix.shape
    rows, columns = X
    print(f"rows: {rows} and columns: {columns}")

function14()

rows: 2 and columns: 3


In [55]:
#15. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.


In [58]:
def function15():
    x = np.diag([1, 2, 3, 4, 5])
    print(x)

function15()

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [59]:
#16. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.


In [63]:
def function16():
    x = np.random.random((3,3,3))
    print(x)

function16()

[[[0.34979155 0.67884344 0.52442357]
  [0.50352921 0.11599593 0.3741711 ]
  [0.30718295 0.79598693 0.92263918]]

 [[0.20526247 0.66151211 0.66437946]
  [0.04172057 0.4372277  0.32182863]
  [0.28876233 0.96032213 0.87332399]]

 [[0.84603882 0.85359575 0.67667343]
  [0.54679003 0.87640139 0.52176857]
  [0.70078331 0.09034597 0.75046408]]]


In [64]:
#17. Write a NumPy program to create a 2x3x4 array filled with arbitrary values.


In [65]:
def function17():
    x = np.random.random((2,3,4))
    print(x)

function17()

[[[0.26203194 0.29836445 0.0245099  0.27907558]
  [0.43860875 0.73412605 0.98318496 0.28491776]
  [0.40098273 0.41263568 0.55532333 0.63317049]]

 [[0.3035926  0.5069706  0.25593283 0.28896114]
  [0.60867871 0.54311407 0.69590415 0.88519545]
  [0.13378078 0.00869367 0.5354828  0.75580575]]]


In [66]:
#18. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.


In [70]:
def function18():
    l =([10,20,30,40,50])
    print(f"original array {l}")
    n1 = np.array(l)
    print(f"1-D numpy array {n1}")

function18()

original array [10, 20, 30, 40, 50]
1-D numpy array [10 20 30 40 50]


In [71]:
#19. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.


In [75]:
def function19():
    a = np.arange(2,11).reshape(3,3)
    print(a)

function19()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [76]:
#20. Write a NumPy program to create an array with values ranging from 12 to 38.


In [77]:
def function20():
    a = np.arange(12,38)
    print(a)

function20()

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [78]:
#21. Write a NumPy program to reverse an array (the first element becomes the last).


In [80]:
def function21():
    int_array = np.array([1,2,3,4,7,8])
    print(int_array)
    a = np.flip(int_array)
    print(a)

function21()

[1 2 3 4 7 8]
[8 7 4 3 2 1]


In [81]:
#22. Write a NumPy program to convert an data type into to a floating type.


In [83]:
def function22():
     
    integer_array = np.array(["1.1", "2.2", "3.3", "4.4"])
    float_array = np.array(integer_array, dtype=float)
    print("Original Array (Integer):", integer_array)
    print("Converted Array (Float):", float_array)


function22()

Original Array (Integer): ['1.1' '2.2' '3.3' '4.4']
Converted Array (Float): [1.1 2.2 3.3 4.4]


In [84]:
#23. Write a NumPy program to convert a list array.

In [91]:
def function23():
    arr = np.array([1,2,3,4,7,8])
    print("Before conversion :",arr)
    print(type(arr))
    arr = list(arr)
    print("\nAfter conversion: ", type(arr))
    print(arr)

function23()

Before conversion : [1 2 3 4 7 8]
<class 'numpy.ndarray'>

After conversion:  <class 'list'>
[1, 2, 3, 4, 7, 8]


In [92]:
#24. Write a NumPy program to get the element-wise remainder of an array of division.


In [93]:
def function24():
    arr1 = np.array([11,23,33,45,55])
    arr2 = np.array([2,4,5,6,9])
    print ("Dividend array : ",arr1) 
    print ("Divisor array : ", arr2) 
    arr = np.remainder(arr1, arr2)  
    print ("Output remainder array: ", arr) 

function24()

Dividend array :  [11 23 33 45 55]
Divisor array :  [2 4 5 6 9]
Output remainder array:  [1 3 3 3 1]


In [1]:
#25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [4]:
def function25():
    x = np.arange(20,50)
    print(f"original array {x}")
    print("after division")
    print(np.true_divide(x, 3)) 

function25()

original array [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
after division
[ 6.66666667  7.          7.33333333  7.66666667  8.          8.33333333
  8.66666667  9.          9.33333333  9.66666667 10.         10.33333333
 10.66666667 11.         11.33333333 11.66666667 12.         12.33333333
 12.66666667 13.         13.33333333 13.66666667 14.         14.33333333
 14.66666667 15.         15.33333333 15.66666667 16.         16.33333333]
